import Head from "next/head";
import styled from "styled-components";
import Navbar from "../components/Navbar";
import PodCard from "../components/PodCard";
import axios from "axios";

export default function Home({ data }) {
  console.log("data", data);
  return (
    <>
      <Head>
        <title>Home - CBS Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeWrapper>
        <Navbar />
        <PodWrapper>
          <PodContainer>
            <PodTitle>Podcasts</PodTitle>
            <PodList>
              {data.map((pod, index) => (
                <PodCard key={index} podcast={pod} />
              ))}
            </PodList>
          </PodContainer>
        </PodWrapper>
      </HomeWrapper>
    </>
  );
}

export async function getServerSideProps() {
  const data = await axios.get("http://localhost:1337/api/podcasts", {
    headers: {
      Authorization: "Bearer " + process.env.STRAPI_SECRET,
    },
  });
  if (data === undefined || data.data === undefined || data.data === null) {
    return {
      notFound: true,
    };
  }
  return {
    props: { data: data.data },
  };
}

const HomeWrapper = styled.div`
  width: 100vw;
  height: 100vh;
  background: #000000;
`;

const PodWrapper = styled.div`
  width: 100vw;
  display: flex;
  justify-content: center;
`;

const PodContainer = styled.div`
  margin-top: 4rem;
  width: 62%;
  min-height: 50vh;
  background-color: #fff;
  padding: 15px;
  border-radius: 5px;
`;

const PodTitle = styled.h1`
  font-family: "Space Grotesk", sans-serif;
  font-size: 2rem;
  font-weight: 700;
  color: #000;
  margin-bottom: 1rem;
  padding-bottom: 1rem;
  border-bottom: 1px solid #000;
`;

const PodList = styled.div`
  display: flex;
  justify-content: flex-start;
  width: 100%;
`;
