import Head from "next/head";
import Navbar from "../components/Navbar";
import styled from "styled-components";

export default function Landing() {
  return (
    <HomeWrapper>
      <Head>
        <title>CBS Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Navbar /> */}
      <PerspectiveGrid>
        <CBSLogo>
          <img src="/CBSLogo.png" alt="CBS Logo" />
        </CBSLogo>
        <PerspectiveGridTitles>
          <h1>CBS</h1>
          <h2>Podcast</h2>
        </PerspectiveGridTitles>
        <PerspectiveGridContent>
          <Button onClick={(e) => (window.location.href = "/home")}>
            Immerse yourself
          </Button>
          <ArrowDown>↓</ArrowDown>
        </PerspectiveGridContent>
      </PerspectiveGrid>
    </HomeWrapper>
  );
}

const HomeWrapper = styled.div`
  width: 100vw;
  height: 100vh;
  background: #100f0f;
`;

const PerspectiveGrid = styled.div`
  font-family: "Space Grotesk", sans-serif;
  width: 100vw;
  height: 100vh;
  background: url("perspectiveGrid.svg") no-repeat center center;
  background-size: cover;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: 106px;
`;

const CBSLogo = styled.div`
  flex: 1;
  display: flex;
  justify-content: center;
  align-items: flex-end;
  img {
    margin-top: 2rem;
    width: 100px;
    height: 100px;
    border-radius: 50%;
  }
`;

const PerspectiveGridTitles = styled.div`
  h1 {
    font-size: 96.94px;
    font-weight: 600;
    background: linear-gradient(
      135deg,
      #a259ff 0%,
      #e667b4 44.27%,
      #fc2d2d 100%
    );
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
  }
  h2 {
    font-size: 96.94px;
    font-weight: 400;
    color: #fff;
  }
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const PerspectiveGridContent = styled.div`
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: center;
  gap: 32px;
`;

const ArrowDown = styled.h1`
  font-size: 96.94px;
  color: #fff;
`;

const Button = styled.button`
  font-family: "Space Grotesk", sans-serif;
  font-size: 36px;
  font-weight: 500;
  color: #0c0f14;
  padding: 15px 30px;
  background-color: #fff;
  box-shadow: 0px 0px 15px 10px rgb(255 255 255 / 15%);
  border: none;
  cursor: pointer;
  transition: all 0.2s ease-in-out;
  :hover {
    color: #fff;
    background-color: #0c0f14;
    box-shadow: none;
  }
  :active {
    color: #0c0f14;
    background-color: #fff;
  }
`;
